name: Code Integration Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
    - "master"

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['react-app', 'server'] }
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ./${{ matrix.dir }}/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: install and build dependencies
        run: yarn install --frozen-lockfile --cwd ./${{ matrix.dir }}

  f-lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ./react-app/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: install
        run: yarn install --frozen-lockfile --cwd ./react-app
      - name: Run test
        run: |
          yarn eslint ./react-app

  b-lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ./server/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: install
        run: yarn install --frozen-lockfile --cwd ./server
      - name: Run test
        run: |
          yarn eslint --cwd ./server

  f-test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ./react-app/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock')}}
      - name: install and build dependencies
        run: yarn install --frozen-lockfile --cwd ./react-app
      - name: Run test
        run: |
          yarn test --cwd ./react-app/src --passWithNoTests 

  b-test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ./server/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: install and build dependencies
        run: yarn install --frozen-lockfile --cwd ./server
      - name: Run test
        run: |
          yarn test --passWithNoTests