name: Code Integration Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
    - "master"

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['react-app', 'server'] }
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ./${{ matrix.dir }}/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: install and build dependencies
        run: yarn install --frozen-lockfile --cwd ./${{ matrix.dir }}

  lint:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['react-app', 'server'] }
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ./${{ matrix.dir }}/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: install
        run: yarn install --frozen-lockfile --cwd ./${{ matrix.dir }}
      - name: Run test
        run: |
          yarn eslint ./src --cwd ./${{ matrix.dir }}

  test:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['react-app', 'server'] }
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ./${{ matrix.dir }}/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock')}}
      - name: install and build dependencies
        run: yarn install --frozen-lockfile --cwd ./${{ matrix.dir }}
      - name: Run test
        run: |
          yarn test --passWithNoTests --cwd ./${{ matrix.dir }}